---
title: "Draft Bargain '22"
author: 
  name: "Max Hübner"
  url: https://maxhuebner.github.io/
date: "`r Sys.Date()`"
output:
  html_document:
    theme: yeti
    toc: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(scales)
library(hubnR)

library(gt)
library(gtExtras)

theme_set(theme_hubnr())
```

TODO TEXT SCHREIBEN

```{r}
fpros <- read_csv("data/draft-bargain/ffpros-ranks-22-08-25.csv") %>% 
  select(rank = 1, name = 3, pos = 5, team = 4) %>% 
  mutate(pos = str_remove(pos, "\\d+"),
         name = str_remove(name, "( II+)|( Jr.)"),
         name = recode(name,
                       "Gabriel Davis" = "Gabe Davis",
                       "Ken Walker" = "Kenneth Walker"),
         team = recode(team,"JAC" = "JAX"),
         pos = recode(pos,"DST" = "DEF"))

underdog <- read_csv("data/draft-bargain/underdog-ranks-22-08-25.csv") %>% 
  select(rank = 7, name = 1, pos = 2, team = 3) %>% 
  mutate(
    team = ifelse(name == "Julio Jones", "TB", team),
    team = recode(team,"LA" = "LAR"),
    name = recode(name,
                  "Gabriel Davis" = "Gabe Davis",
                  "D.K. Metcalf" = "DK Metcalf")
  )

sleeper <- read_csv("data/draft-bargain/sleeper-mock-ranks-2022-08-25.csv") %>% 
  filter(!team %in% c("QUES", "PUP"))
```


```{r}
sleeper %>% 
  anti_join(underdog, by=c("name","team", "pos"))

underdog %>% 
  anti_join(sleeper, by=c("name","team", "pos"))
```

```{r}
adp <- sleeper %>% 
  left_join(fpros, by=c("name","team", "pos"), suffix = c("_sleeper","_fpros")) %>% 
  left_join(underdog, by=c("name","team", "pos")) %>% 
  rename(rank_ud = rank) %>% 
  relocate(rank_sleeper, .before = rank_fpros) %>% 
  mutate(diff_fpros = rank_sleeper - rank_fpros,
         diff_ud = rank_sleeper - rank_ud)
  
```

```{r}
gt_adp <- . %>% 
  gt() %>% 
  gt_theme_538() %>% 
  cols_label(
    rank_sleeper = "Sleeper",
    rank_fpros = "FPros",
    rank_ud = "Underdog",
    diff_fpros = "FPr",
    diff_ud = "UD"
  ) %>% 
  tab_spanner("Ranks", 4:6) %>% 
  tab_spanner("Difference", 7:8) %>% 
  tab_options(column_labels.text_transform = "capitalize",
              row_group.text_transform = "capitalize") %>% 
  fmt_missing(everything(), missing_text = "-")
  
```

```{r}
color_pos <- . %>% 
  mutate(pos = recode(pos,
                      "QB" = '<span style="color:#C05E85"><b>QB</b></span>',
                      "WR" = '<span style="color:#46A2CA"><b>WR</b></span>',
                      "RB" = '<span style="color:#73C3A6"><b>RB</b></span>',
                      "TE" = '<span style="color:#CC8C4A"><b>TE</b></span>'))
```

```{r}
gt_fp_s_qbte <- adp %>% 
  filter(rank_sleeper <= 180,
         pos %in% c("TE", "QB")) %>% 
  arrange(desc(diff_fpros)) %>% #CC8C4A#C05E85
  group_by(pos) %>% 
  group_modify(~head(.,8)) %>% 
  ungroup() %>% 
  gt_adp() %>% 
  tab_header("Draft Bargain '22 - Fantasy Pros Steals",
             subtitle = md('<span style="color:#C05E85"><b>QBs</b></span> und <span style="color:#CC8C4A"><b>TEs</b></span> welche bei Fantasy Pros deutlich früher gepickt werden')) %>% 
  tab_row_group(label = html('<span style="color:#C05E85"><b>Quarterbacks</b></span>'), rows = pos == "QB") %>% 
  tab_row_group(label = html('<span style="color:#CC8C4A"><b>Tight Ends</b></span>'), rows = pos == "TE") %>% 
  gt_color_rows("diff_fpros", palette = "ggsci::teal_material") %>% 
  cols_hide("pos")

gtsave_extra(gt_fp_s_qbte, "export/db22/gt_fp_s_qbte.png", expand = 0, zoom = 5)
gt_fp_s_qbte
```

```{r}
gt_fp_s_rb <- adp %>% 
  filter(rank_sleeper <= 180,
         pos == "RB") %>% 
  arrange(desc(diff_fpros)) %>%
  head(14) %>% 
  gt_adp() %>% 
  gt_color_rows("diff_fpros", palette = "ggsci::teal_material") %>% 
  tab_header("Draft Bargain '22 - Fantasy Pros Steals",
             subtitle = md('<span style="color:#73C3A6"><b>Running Backs</b></span> welche bei Fantasy Pros deutlich früher gepickt werden'))

gtsave_extra(gt_fp_s_rb, "export/db22/gt_fp_s_rb.png", expand = 0, zoom = 5)
gt_fp_s_rb
```

```{r}
gt_fp_s_wr <- adp %>% 
  filter(rank_sleeper <= 180,
         pos == "WR") %>% 
  arrange(desc(diff_fpros)) %>%
  head(14) %>% 
  gt_adp() %>% 
  gt_color_rows("diff_fpros", palette = "ggsci::teal_material") %>% 
  tab_header("Draft Bargain '22 - Fantasy Pros Steals",
             subtitle = md('<span style="color:#46A2CA"><b>Wide Receivers</b></span> welche bei Fantasy Pros deutlich früher gepickt werden'))

gtsave_extra(gt_fp_s_wr, "export/db22/gt_fp_s_wr.png", expand = 0, zoom = 5)
gt_fp_s_wr
```

```{r}
gt_fp_s <- adp %>% 
  filter(rank_sleeper <= 60) %>% 
  arrange(desc(diff_fpros)) %>%
  head(12) %>% 
  color_pos() %>% 
  gt_adp() %>% 
  gt_color_rows("diff_fpros", palette = "ggsci::teal_material") %>% 
  tab_header("Draft Bargain '22 - Fantasy Pros Overall Steals",
             subtitle = md('Die besten Steals **aus den ersten 6 Runden**')) %>% 
  fmt_markdown(pos)

gtsave_extra(gt_fp_s, "export/db22/gt_fp_s.png", expand = 0, zoom = 5)
gt_fp_s
```

### Overhyped

```{r}
gt_fp_o_qbte <- adp %>% 
  filter(rank_sleeper <= 180,
         pos %in% c("TE", "QB")) %>% 
  arrange(diff_fpros) %>%
  group_by(pos) %>% 
  group_modify(~head(.,8)) %>% 
  ungroup() %>% 
  gt_adp() %>% 
  gt_color_rows("diff_fpros", reverse = T, palette = "ggsci::amber_material") %>% 
  tab_header("Draft Bargain '22 - Fantasy Pros Overhyped",
             subtitle = md('<span style="color:#C05E85"><b>QBs</b></span> und <span style="color:#CC8C4A"><b>TEs</b></span> welche bei Fantasy Pros deutlich **später** gepickt werden')) %>% 
  tab_row_group(label = html('<span style="color:#C05E85"><b>Quarterbacks</b></span>'), rows = pos == "QB") %>% 
  tab_row_group(label = html('<span style="color:#CC8C4A"><b>Tight Ends</b></span>'), rows = pos == "TE") %>% 
  cols_hide("pos")

gtsave_extra(gt_fp_o_qbte, "export/db22/gt_fp_o_qbte.png", expand = 0, zoom = 5)
gt_fp_o_qbte
```

```{r}
gt_fp_o_rb <- adp %>% 
  filter(rank_sleeper <= 180,
         pos == "RB") %>% 
  arrange(diff_fpros) %>%
  head(14) %>% 
  gt_adp() %>% 
  gt_color_rows("diff_fpros", reverse = T, palette = "ggsci::amber_material") %>% 
  tab_header("Draft Bargain '22 - Fantasy Pros Overhyped",
             subtitle = md('<span style="color:#73C3A6"><b>Running Backs</b></span> welche bei Fantasy Pros deutlich **später** gepickt werden'))

gtsave_extra(gt_fp_o_rb, "export/db22/gt_fp_o_rb.png", expand = 0, zoom = 5)
gt_fp_o_rb
```

```{r}
gt_fp_o_wr <- adp %>% 
  filter(rank_sleeper <= 180,
         pos == "WR") %>% 
  arrange(diff_fpros) %>%
  head(14) %>% 
  gt_adp() %>% 
  gt_color_rows("diff_fpros", reverse = T, palette = "ggsci::amber_material") %>% 
  tab_header("Draft Bargain '22 - Fantasy Pros Overhyped",
             subtitle = md('<span style="color:#46A2CA"><b>Wide Receivers</b></span> welche bei Fantasy Pros deutlich **später** gepickt werden'))

gtsave_extra(gt_fp_o_wr, "export/db22/gt_fp_o_wr.png", expand = 0, zoom = 5)
gt_fp_o_wr
```

```{r}
gt_fp_o <- adp %>% 
  filter(rank_sleeper <= 60) %>% 
  arrange(diff_fpros) %>%
  head(12) %>% 
  color_pos() %>% 
  gt_adp() %>% 
  gt_color_rows("diff_fpros", reverse = T, palette = "ggsci::amber_material") %>% 
  tab_header("Draft Bargain '22 - Fantasy Pros Overall Overhyped",
             subtitle = md('Die schlechtesten Steals **aus den ersten 6 Runden**')) %>% 
  fmt_markdown(pos)

gtsave_extra(gt_fp_o, "export/db22/gt_fp_o.png", expand = 0, zoom = 5)
gt_fp_o
```

### Kurze Blick auf Underdog ADP

```{r}
gt_ud_s <- adp %>% 
  filter(rank_sleeper <= 80) %>% 
  arrange(desc(diff_ud)) %>% 
  head(16) %>% 
  color_pos() %>% 
  gt_adp() %>% 
  gt_color_rows("diff_ud", palette = "ggsci::teal_material") %>% 
  tab_header("Draft Bargain '22 - Underdog Overall Steals",
             subtitle = md('Die besten Steals **aus den ersten 8 Runden**')) %>% 
  fmt_markdown(pos)

gtsave_extra(gt_ud_s, "export/db22/gt_ud_s.png", expand = 0, zoom = 5)
gt_ud_s
```

```{r}
gt_ud_o <- adp %>% 
  filter(rank_sleeper <= 80) %>% 
  arrange(diff_ud) %>% 
  head(16) %>% 
  color_pos() %>% 
  gt_adp() %>% 
  gt_color_rows("diff_fpros", reverse = T, palette = "ggsci::amber_material") %>%
  tab_header("Draft Bargain '22 - Underdog Overall Overhyped",
             subtitle = md('Die schlechtesten Steals **aus den ersten 8 Runden**')) %>% 
  fmt_markdown(pos)

gtsave_extra(gt_ud_o, "export/db22/gt_ud_o.png", expand = 0, zoom = 5)
gt_ud_o
```

